name: selfie_video_app
description: A Flutter app for creating, editing, and sharing selfie videos with teleprompter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.4
  
  # Camera and video
  camera: ^0.10.5+5
  video_player: ^2.7.2
  
  # Video editing
  video_editor_2: ^3.1.1
  
  # Storage and utilities
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  
  # UI components
  flutter_spinkit: ^5.2.0
  
  # Social media sharing
  share_plus: ^7.2.1
  
  # HTTP client for mock API
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.2
  build_runner: ^2.4.6


dependency_overrides:  
  get_thumbnail_video: ^0.7.3


flutter:
  uses-material-design: true
  assets:
    - assets/images/

